### ISSUE TITLE
Make swals look better on phone

### ISSUE THREAD

**Issue by jkbngl** [jkbngl/trainingsplan#71]

**Comment by jkbngl** [comment]
``` css
.mobile_swal {
  font-size: 2rem !important;
}
```

The important tag overwrites the default style
